@WebApi_HostAddress = https://localhost:7119

GET {{WebApi_HostAddress}}/api/persons/00000000-0000-0000-0000-000000000000
Accept: application/json

###
POST {{WebApi_HostAddress}}/api/persons
Content-Type: application/json

{
  "code": "ABC123",
  "firstName": "Juan",
  "lastName": "Perez",
  "email": "juan.perez@example.com",
  "phoneNumber": "1234567890"
}

###
GET {{WebApi_HostAddress}}/api/persons
Accept: application/json

###
PUT {{WebApi_HostAddress}}/api/persons/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "code": "ABC123",
  "firstName": "Juan",
  "lastName": "Perez",
  "email": "juan.perez@example.com",
  "phoneNumber": "1234567890"
}

###
DELETE {{WebApi_HostAddress}}/api/persons/00000000-0000-0000-0000-000000000000

###
GET {{WebApi_HostAddress}}/api/persons/code/